### ISSUE TITLE
Add 'search' command that searches all attributes in Person

### ISSUE THREAD

**Issue by zenghou** [CS2103AUG2017-F11-B4/main#23]
### Title of User Story: 
- As a user I can search for contacts by other fields (e.g. email/address/contact number)

### Description: 
- This feature allows the user to quickly access contact by other identifiable attributes 

### Tasks: 
- [x] Logic: teach application to accept `search` command 
- [x] Model: implement `DetailsContainKeyphrasePredicate` class
- [x] Logic: teach application to accept `search` arguments 
- [x] Logic: Implement `SearchCommand#execute()`
- [x] View: Display the result on UI 
- [x] Model: add case-insensitivity in `DetailsContainKeyphrasePredicate`
